language: php
php:
  - 5.6

addons:
  ssh_known_hosts: git.wpengine.com

before_install:
  - openssl aes-256-cbc -K $encrypted_acb32be6362e_key -iv $encrypted_acb32be6362e_iv
    -in travis_key_rsa.pem.enc -out travis_key_rsa.pem -d

script:
  - php test.php

after_success:
  - chmod 600 travis_key_rsa.pem # this key should have push access
  - ssh-add travis_key_rsa.pem
  - git remote add deploy git@git.wpengine.com:production/sucommunity.git
  - git push deploy master
